import { Ionicons } from "@expo/vector-icons"

export const Icons = {
    onboardingOne: require('../assets/images/onboardingOne.png'),
    onboardingTwo: require('../assets/images/onboardingTwo.png'),
    onboardingThree: require('../assets/images/onboardingThree.png'),
    onboardingFour: require('../assets/images/onboardingFour.png'),
    arrowRight: require('../assets/images/icons8-arrow-100.png'),
    logo: require('../assets/images/logo.png'),
    google: require('../assets/images/search.png'),
    apple: require('../assets/images/apple-logo.png'),
    like: require('../assets/images/icons8-like-96.png'),
    comment: require('../assets/images/icons8-comment-96.png'),
    share: require('../assets/images/icons8-share-96.png'),
    bookmark: require('../assets/images/icons8-bookmark-96.png'),
    menu: require('../assets/images/icons8-menu-96.png'),
    search: require('../assets/images/icons8-search-90.png'),
    plus: require('../assets/images/icons8-plus-128.png'),
    book: require('../assets/images/icons8-book-96.png'),
    profile: require('../assets/images/icons8-person-64.png'),
    home: require('../assets/images/icons8-home-96.png'),
    verifiedBadge: require('../assets/images/verifiedBadge.png'),
    menuH: require('../assets/images/icons8-menu-67.png'),
    notification: require('../assets/images/icons8-notification-100.png'),
    chat: require('../assets/images/icons8-chat-64.png'),
    bookmarkW: require('../assets/images/icons8-bookmark-90.png'),
    back: require('../assets/images/icons8-back-96.png'),
    reward: require('../assets/images/reward.png'),
    points: require('../assets/images/points.png'),
    medal: require('../assets/images/goldMedal.png'),
    backgroundS: require('../assets/images/backgroundStylish.png'),
    filter: require('../assets/images/filter.png'),
    quiz: require('../assets/images/quiz.png'),
}